---
name: XML-Quick
version: 0.03
author:
  - 'Robert Norris <Robert.Norris@its.monash.edu.au>'
abstract: Generate XML from hashes (and other data)
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  XML::Quick:
    file: lib/XML/Quick.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
